<template><div><h4 id="px-和-rpx-的转化" tabindex="-1"><a class="header-anchor" href="#px-和-rpx-的转化"><span>px 和 rpx 的转化</span></a></h4>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">px(pixel)</span><span class="token template-punctuation string">`</span></span>和<span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">rpx(responsive pixel)</span><span class="token template-punctuation string">`</span></span>也都是用于度量长度的单位<span class="token punctuation">,</span>但是它们有不同的换算关系。px是绝对单位<span class="token punctuation">,</span>1px <span class="token operator">=</span> <span class="token number">1</span><span class="token operator">/</span><span class="token number">96</span>寸。在不同设备上<span class="token punctuation">,</span>1px对应不同的物理尺寸<span class="token punctuation">,</span>所以不适合用于响应式布局。rpx是相对单位<span class="token punctuation">,</span>它是相对于屏幕宽度来计算的。在iPhone <span class="token number">6</span>上<span class="token punctuation">,</span>屏幕宽度为750px<span class="token punctuation">,</span>所以750rpx <span class="token operator">=</span> 1px。
在iPhone <span class="token constant">X</span>上<span class="token punctuation">,</span>屏幕宽度为1125px<span class="token punctuation">,</span>所以1125rpx <span class="token operator">=</span> 1px。所以<span class="token punctuation">,</span><span class="token literal-property property">px和rpx的换算关系为</span><span class="token operator">:</span>rpx <span class="token operator">=</span> px <span class="token function">×</span> <span class="token punctuation">(</span>设备宽度 <span class="token operator">/</span> 标准宽度<span class="token punctuation">)</span>标准宽度一般为750px。例如<span class="token operator">:</span>
<span class="token operator">-</span> 在<span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">iPhone 6</span><span class="token template-punctuation string">`</span></span><span class="token function">上</span><span class="token punctuation">(</span>屏幕宽度750px<span class="token punctuation">)</span><span class="token operator">:</span>
<span class="token operator">-</span> 设定元素width<span class="token operator">:</span> 150rpx
<span class="token operator">-</span> 那么这个元素的px宽度就是<span class="token operator">:</span> 150rpx <span class="token operator">*</span> 750px <span class="token operator">/</span> <span class="token number">750</span> <span class="token operator">=</span> 150px
<span class="token operator">-</span> 在<span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">iPhone X</span><span class="token template-punctuation string">`</span></span><span class="token function">上</span><span class="token punctuation">(</span>屏幕宽度1125px<span class="token punctuation">)</span><span class="token operator">:</span>
<span class="token operator">-</span> 设定元素width<span class="token operator">:</span> 150rpx
<span class="token operator">-</span> 那么这个元素的px宽度就是<span class="token operator">:</span> 150rpx <span class="token operator">*</span> 1125px <span class="token operator">/</span> <span class="token number">750</span> <span class="token operator">=</span> 225px可以看出<span class="token punctuation">,</span>在不同屏幕宽度的设备上<span class="token punctuation">,</span>rpx对应的px值会不同<span class="token punctuation">,</span>这就是rpx实现响应式的原理。在小程序开发中<span class="token punctuation">,</span>我们通常会根据标准宽度750px来设计<span class="token constant">UI</span><span class="token punctuation">,</span>然后使用rpx作为单位。在不同设备上<span class="token punctuation">,</span>rpx会自动转换为对应的px值<span class="token punctuation">,</span>实现响应式布局
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="开发者可以通过设计稿基准宽度计算页面元素-rpx-值-设计稿-1px-与框架样式-1rpx-转换公式如下" tabindex="-1"><a class="header-anchor" href="#开发者可以通过设计稿基准宽度计算页面元素-rpx-值-设计稿-1px-与框架样式-1rpx-转换公式如下"><span>开发者可以通过设计稿基准宽度计算页面元素 <code v-pre>rpx</code> 值，设计稿 <code v-pre>1px</code> 与框架样式 <code v-pre>1rpx</code> 转换公式如下：</span></a></h4>
<p><code v-pre>设计稿 1px / 设计稿基准宽度 = 框架样式 1rpx / 750rpx</code></p>
<p>换言之，页面元素宽度在 uni-app 中的宽度计算公式：</p>
<p><code v-pre>750 * 元素在设计稿中的宽度 / 设计稿基准宽度</code></p>
</div></template>


